### PR TITLE
Create a Dockerfile

### PR DESCRIPTION
**Pull request by Leprechaunz**
Issue #5 

Could somebody please test this PR and check if album has right url?
On my machine I'm getting `index.php`, but it shouldn't appear in URL

### CODE REVIEW

**Comment by mre** [comment]
Had to do a few changes.
With that, I can call the site from `/`. Somehow the image thumbnails don't work though. Don't know what's going on there. 
Check out the [docker2](https://github.com/mre/unicorn/tree/docker2) branch.
Feel free to merge the changes into your branch and we go from there.

**Comment by Leprechaunz** [comment]
@mre I'm still working on it
Thumbnails are OK for me. Try remove cache and recheck.

But when I enter http://localhost:8080/
I get album url like http://localhost:8080/index.php/Test This link is not working
At same time http://localhost:8080/Test is correct and works as expected.

Should correct album link contain `index.php`?

**Comment by mre** [comment]
I don't know to be honest. We should look at a few other Slim applications to see what they're doing.

**Comment by Leprechaunz** [comment]
@mre Added using Slim Router to avoid index.php in routes
Please check if thumbnails are showing now

**Comment by florianorben** [comment]
@mre I somehow totally missed this PR sorry, feel free to close https://github.com/mre/unicorn/pull/12 if it isnt needed :)

**Comment by Leprechaunz** [comment]
@mre I merge some features from #12 
Moved config keys to env variables inside of `docker-composer.yml`. Maybe later we will need to move them into `.env` file.

@florianorben Not sure if we need `nginx.conf`. Do we really need it? What do you think?

**Pull request merged**
